# -*- coding: utf-8 -*-
"""Sharpening_image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kFBznAB525FXLt9ZepnnYPzUbLIxhmVT
"""

import cv2
from google.colab.patches import cv2_imshow

img1 = cv2.imread('/content/reticulated_python.jpg',1)
filter = np.array([[-1, -1, -1], [-1, 10, -1], [-1, -1, -1]])
sharpen_img_1=cv2.filter2D(img1,-1,filter)
cv2_imshow(sharpen_img_1)
img2 = cv2.imread('/content/rottweiler.jpg',1)
filter = np.array([[-1, -1, -1], [-1, 12, -1], [-1, -1, -1]])
sharpen_img_2=cv2.filter2D(img2,-1,filter)
cv2_imshow(sharpen_img_2)



